---
title: Welcome
author: Thomas Klebel
date: '2017-10-28'
slug: welcome
categories:
  - General
tags: []
---

There are numerous reasons, why one would have a personal blog or website. Over
the last few weeks, quite a few of them accumulated until I thought, I'd give it
a go.
Besides the urge of having a place where I could develop ideas and comment on 
certain topics, in a few weeks time I will give a talk together with a colleague
at a conference, and we plan to make available some intermediate outcomes of our
research, in this case a package for R which I wrote. This site will
be a very good place to showcase the package and further directions our research
might take.

So, what content are you going to find here in the future? I plan to write about
small or larger (coding) projects I take on, about my developing research, and
probably some random thoughts about Austrian politics and society.

Starting a blog with the use of blogdown feels almost like cheating -- for sure,
there are aspects to learn, options to set, problems to wrap your head around. 
But all in all, the process is quite straightforward, thanks to
Yihui Xie's [package](https://github.com/rstudio/blogdown)
and the most helpful documentation at https://bookdown.org/yihui/blogdown/.

In starting website with a blog I want to mention a few sites I really enjoy
reading, and to which I owe inspirational credit for my own page:

- https://rud.is/b/ by Bob Rudis
- https://juliasilge.com by Julia Silge
- http://varianceexplained.org by David Robinson
- http://www.masalmon.eu/ by Maëlle Salmon
- https://www.data-imaginist.com by Thomas Lin Pedersen

A special piece of inspiration was a series of posts
([1](http://www.masalmon.eu/2017/04/23/radioswissclassic/),
[2](http://www.masalmon.eu/2017/04/30/radioedit/)) by Maëlle about the music
which airs on *Radio Swiss classic*. I wondered, how the program of 
Austrian radio stations like [radio klassik Stephansdom](https://radioklassik.at)
would compare, and I will try to explore this comparison in one of my future posts.




